export const dynamic = "force-dynamic"

import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const space_grotesk = Space_Grotesk({ subsets: ['latin'], weight: ['400', '500', '700'] })
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { CartProvider } from "@/components/CartContextProvider";
import { getDataFromToken } from "@/helper/getDataFromToken";
import AdminSideBar from "@/components/layout/admin/AdminSideBar";
import AdminHeader from "@/components/layout/admin/AdminHeader";

export const metadata = {
  title: "Gourmify",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const data = await getDataFromToken()
  if (data?.isAdmin === true) {
    return (
      <html lang="en" className="overflow-x-hidden" >
        <head>
            <title>Gourmify</title>
            <link rel="icon" href="/favicon.png" ></link>
        </head>
        <body className={space_grotesk.className}>
          <div className="select-none">
            <AdminSideBar />
            <AdminHeader />
            <main className=" mx-auto p-3 ">
              {children}
            </main>
          </div>
        </body>
      </html>
    )
  }
  else {
    return (
      <html lang="en" className="overflow-x-hidden" >
        <head>
          <title>Gourmify</title>
          <link rel="icon" href="/favicon.png" ></link>
        </head>
        <body className={space_grotesk.className}>
          <CartProvider>
            <div className="select-none">
              <Header title={"GOURMIFY"} />
              <main className=" min-w-4xl max-w-4xl md:min-w-6xl md:max-w-6xl  mx-auto p-3  ">
                {children}
              </main>
              <Footer />
            </div>
          </CartProvider>
        </body>
      </html>
    )
  }
}